export const TOOLS = [
  {
    id: 'image-converter',
    name: '이미지 포맷 변환기',
    description: 'JPG, PNG, WEBP 등 다양한 이미지 포맷을 변환합니다.',
    category: 'image-tools',
    icon: '🖼️',
    isNew: false,
    path: '/image-tools/image-converter',
  },
  {
    id: 'image-resizer',
    name: '이미지 리사이저',
    description: '이미지 크기를 간편하게 조절합니다.',
    category: 'image-tools',
    icon: '📐',
    isNew: false,
    path: '/image-tools/image-resizer',
  },
  {
    id: 'text-comparator',
    name: '텍스트 비교 도구',
    description: '두 개의 텍스트를 비교하여 차이점을 찾습니다.',
    category: 'text',
    icon: '🔍',
    isNew: true, // 이 툴에 NEW 배지 표시
    path: '/text/text-comparator',
  },
  {
    id: 'text-transformer',
    name: '텍스트 변환 도구',
    description: '대소문자 변환, 줄바꿈/공백 제거 등 텍스트를 정리합니다.',
    category: 'text',
    icon: '✍️',
    isNew: false,
    path: '/text/text-transformer',
  },
  {
    id: 'word-counter',
    name: '글자수/단어수 계산기',
    description: '공백 포함/미포함 글자수와 단어수를 세어줍니다.',
    category: 'text',
    icon: '🔢',
    isNew: true,
    path: '/text/word-counter',
  },
  {
    id: 'd-day-counter',
    name: '디데이 계산기',
    description: '특정 날짜까지 남은 날짜를 계산합니다.',
    category: 'date-time',
    icon: '🗓️',
    isNew: false,
    path: '/date-time/d-day-counter',
  },
  {
    id: 'age-calculator',
    name: '나이 계산기',
    description: '생년월일을 바탕으로 나이를 계산해줍니다.',
    category: 'date-time',
    icon: '🎂',
    isNew: false,
    path: '/date-time/age-calculator',
  },
];