import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Header from "@/components/main/Header";
import Footer from "@/components/main/Footer";

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"], // 일반(400) 두께와 굵은(700) 두께를 사용할게요.
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${figtree.className} antialiased flex min-h-screen flex-col`}>
        <Header />
        <main className="flex flex-grow flex-col">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
